// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: consensus/pbft/pbft.proto

package pbft

import (
	common "chainmaker.org/chainmaker/pb-go/v2/common"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = io.EOF
var _ = math_bits.Len

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// PBFTMsgType defines different type message in pbft
type PBFTMsgType int32

const (
	PBFTMsgType_MSG_PREPREPARE  PBFTMsgType = 0
	PBFTMsgType_MSG_PREPARE     PBFTMsgType = 1
	PBFTMsgType_MSG_COMMIT      PBFTMsgType = 2
	PBFTMsgType_MSG_VIEWCHANGE  PBFTMsgType = 3
	PBFTMsgType_MSG_NEWVIEW     PBFTMsgType = 4
	PBFTMsgType_MSG_REQUEST_OLD PBFTMsgType = 5
	PBFTMsgType_MSG_SEND_OLD    PBFTMsgType = 6
	PBFTMsgType_MSG_STATE       PBFTMsgType = 7
)

var PBFTMsgType_name = map[int32]string{
	0: "MSG_PREPREPARE",
	1: "MSG_PREPARE",
	2: "MSG_COMMIT",
	3: "MSG_VIEWCHANGE",
	4: "MSG_NEWVIEW",
	5: "MSG_REQUEST_OLD",
	6: "MSG_SEND_OLD",
	7: "MSG_STATE",
}

var PBFTMsgType_value = map[string]int32{
	"MSG_PREPREPARE":  0,
	"MSG_PREPARE":     1,
	"MSG_COMMIT":      2,
	"MSG_VIEWCHANGE":  3,
	"MSG_NEWVIEW":     4,
	"MSG_REQUEST_OLD": 5,
	"MSG_SEND_OLD":    6,
	"MSG_STATE":       7,
}

func (x PBFTMsgType) String() string {
	return proto.EnumName(PBFTMsgType_name, int32(x))
}

func (PBFTMsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pbft_consensus, []int{0}
}

// PBFTStep represents the step in pbft consensus
type PBFTStep int32

const (
	PBFTStep_NEW_HEIGHT    PBFTStep = 0
	PBFTStep_PRE_PREPARE   PBFTStep = 1
	PBFTStep_PREPARE       PBFTStep = 2
	PBFTStep_COMMIT        PBFTStep = 3
	PBFTStep_COMMITTED     PBFTStep = 4
	PBFTStep_VIEW_CHANGE   PBFTStep = 5
	PBFTStep_NEW_VIEW      PBFTStep = 6
)

var PBFTStep_name = map[int32]string{
	0: "NEW_HEIGHT",
	1: "PRE_PREPARE",
	2: "PREPARE",
	3: "COMMIT",
	4: "COMMITTED",
	5: "VIEW_CHANGE",
	6: "NEW_VIEW",
}

var PBFTStep_value = map[string]int32{
	"NEW_HEIGHT":   0,
	"PRE_PREPARE":  1,
	"PREPARE":      2,
	"COMMIT":       3,
	"COMMITTED":    4,
	"VIEW_CHANGE":  5,
	"NEW_VIEW":     6,
}

func (x PBFTStep) String() string {
	return proto.EnumName(PBFTStep_name, int32(x))
}

func (PBFTStep) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pbft_consensus, []int{1}
}

// WalEntryType represents different types of entries in Wal
type WalEntryType int32

const (
	WalEntryType_TIMEOUT_ENTRY       WalEntryType = 0
	WalEntryType_PREPREPARE_ENTRY    WalEntryType = 1
	WalEntryType_PREPARE_ENTRY       WalEntryType = 2
	WalEntryType_COMMIT_ENTRY        WalEntryType = 3
	WalEntryType_VIEWCHANGE_ENTRY    WalEntryType = 4
	WalEntryType_NEWVIEW_ENTRY       WalEntryType = 5
	WalEntryType_PREPREPARE_PREPARE_ENTRY WalEntryType = 6
)

var WalEntryType_name = map[int32]string{
	0: "TIMEOUT_ENTRY",
	1: "PREPREPARE_ENTRY",
	2: "PREPARE_ENTRY",
	3: "COMMIT_ENTRY",
	4: "VIEWCHANGE_ENTRY",
	5: "NEWVIEW_ENTRY",
	6: "PREPREPARE_PREPARE_ENTRY",
}

var WalEntryType_value = map[string]int32{
	"TIMEOUT_ENTRY":             0,
	"PREPREPARE_ENTRY":          1,
	"PREPARE_ENTRY":             2,
	"COMMIT_ENTRY":              3,
	"VIEWCHANGE_ENTRY":          4,
	"NEWVIEW_ENTRY":             5,
	"PREPREPARE_PREPARE_ENTRY":  6,
}

func (x WalEntryType) String() string {
	return proto.EnumName(WalEntryType_name, int32(x))
}

func (WalEntryType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_pbft_consensus, []int{2}
}

// ValidatorSet represents the set of validators
type ValidatorSet struct {
	Validators []string `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators,omitempty"`
}

func (m *ValidatorSet) Reset()         { *m = ValidatorSet{} }
func (m *ValidatorSet) String() string { return proto.CompactTextString(m) }
func (*ValidatorSet) ProtoMessage()    {}
func (*ValidatorSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_pbft_consensus, []int{0}
}

func (m *ValidatorSet) GetValidators() []string {
	if m != nil {
		return m.Validators
	}
	return nil
}

// PBFTMsg is the wrapper message for all pbft messages
type PBFTMsg struct {
	Type PBFTMsgType `protobuf:"varint,1,opt,name=type,proto3,enum=pbft.PBFTMsgType" json:"type,omitempty"`
	Msg  []byte      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *PBFTMsg) Reset()         { *m = PBFTMsg{} }
func (m *PBFTMsg) String() string { return proto.CompactTextString(m) }
func (*PBFTMsg) ProtoMessage()    {}
func (*PBFTMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_pbft_consensus, []int{1}
}

func (m *PBFTMsg) GetType() PBFTMsgType {
	if m != nil {
		return m.Type
	}
	return PBFTMsgType_MSG_PREPREPARE
}

func (m *PBFTMsg) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

// PrePrepare represents a pre-prepare message in pbft
type PrePrepare struct {
	Primary      string                     `protobuf:"bytes,1,opt,name=primary,proto3" json:"primary,omitempty"`
	View         uint64                     `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	Sequence     uint64                     `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Digest       []byte                     `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	Block        *common.Block              `protobuf:"bytes,5,opt,name=block,proto3" json:"block,omitempty"`
	Endorsement  *common.EndorsementEntry   `protobuf:"bytes,6,opt,name=endorsement,proto3" json:"endorsement,omitempty"`
	TxsRwSet     map[string]*common.TxRWSet `protobuf:"bytes,7,rep,name=txs_rw_set,json=txsRwSet,proto3" json:"txs_rw_set,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *PrePrepare) Reset()         { *m = PrePrepare{} }
func (m *PrePrepare) String() string { return proto.CompactTextString(m) }
func (*PrePrepare) ProtoMessage()    {}
func (*PrePrepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_pbft_consensus, []int{2}
}

func (m *PrePrepare) GetPrimary() string {
	if m != nil {
		return m.Primary
	}
	return ""
}

func (m *PrePrepare) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *PrePrepare) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *PrePrepare) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *PrePrepare) GetBlock() *common.Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *PrePrepare) GetEndorsement() *common.EndorsementEntry {
	if m != nil {
		return m.Endorsement
	}
	return nil
}

func (m *PrePrepare) GetTxsRwSet() map[string]*common.TxRWSet {
	if m != nil {
		return m.TxsRwSet
	}
	return nil
}

// Prepare represents a prepare message in pbft
type Prepare struct {
	NodeId    string                   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	View      uint64                   `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	Sequence  uint64                   `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Digest    []byte                   `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	Endorsement *common.EndorsementEntry `protobuf:"bytes,5,opt,name=endorsement,proto3" json:"endorsement,omitempty"`
}

func (m *Prepare) Reset()         { *m = Prepare{} }
func (m *Prepare) String() string { return proto.CompactTextString(m) }
func (*Prepare) ProtoMessage()    {}
func (*Prepare) Descriptor() ([]byte, []int) {
	return fileDescriptor_pbft_consensus, []int{3}
}

func (m *Prepare) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *Prepare) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Prepare) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Prepare) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *Prepare) GetEndorsement() *common.EndorsementEntry {
	if m != nil {
		return m.Endorsement
	}
	return nil
}

// Commit represents a commit message in pbft
type Commit struct {
	NodeId      string                   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	View        uint64                   `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	Sequence    uint64                   `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Digest      []byte                   `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	Endorsement *common.EndorsementEntry `protobuf:"bytes,5,opt,name=endorsement,proto3" json:"endorsement,omitempty"`
}

func (m *Commit) Reset()         { *m = Commit{} }
func (m *Commit) String() string { return proto.CompactTextString(m) }
func (*Commit) ProtoMessage()    {}
func (*Commit) Descriptor() ([]byte, []int) {
	return fileDescriptor_pbft_consensus, []int{4}
}

func (m *Commit) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *Commit) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *Commit) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Commit) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *Commit) GetEndorsement() *common.EndorsementEntry {
	if m != nil {
		return m.Endorsement
	}
	return nil
}

// ViewChange represents a view-change message in pbft
type ViewChange struct {
	NodeId      string                   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CurView     uint64                   `protobuf:"varint,2,opt,name=cur_view,json=curView,proto3" json:"cur_view,omitempty"`
	NextView    uint64                   `protobuf:"varint,3,opt,name=next_view,json=nextView,proto3" json:"next_view,omitempty"`
	Sequence    uint64                   `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Endorsement *common.EndorsementEntry `protobuf:"bytes,5,opt,name=endorsement,proto3" json:"endorsement,omitempty"`
}

func (m *ViewChange) Reset()         { *m = ViewChange{} }
func (m *ViewChange) String() string { return proto.CompactTextString(m) }
func (*ViewChange) ProtoMessage()    {}
func (*ViewChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_pbft_consensus, []int{5}
}

func (m *ViewChange) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ViewChange) GetCurView() uint64 {
	if m != nil {
		return m.CurView
	}
	return 0
}

func (m *ViewChange) GetNextView() uint64 {
	if m != nil {
		return m.NextView
	}
	return 0
}

func (m *ViewChange) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ViewChange) GetEndorsement() *common.EndorsementEntry {
	if m != nil {
		return m.Endorsement
	}
	return nil
}

// NewView represents a new-view message in pbft
type NewView struct {
	NodeId      string                   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CurView     uint64                   `protobuf:"varint,2,opt,name=cur_view,json=curView,proto3" json:"cur_view,omitempty"`
	NextView    uint64                   `protobuf:"varint,3,opt,name=next_view,json=nextView,proto3" json:"next_view,omitempty"`
	NewSequence uint64                   `protobuf:"varint,4,opt,name=new_sequence,json=newSequence,proto3" json:"new_sequence,omitempty"`
	ViewChangeMessages []*ViewChange     `protobuf:"bytes,5,rep,name=view_change_messages,json=viewChangeMessages,proto3" json:"view_change_messages,omitempty"`
	Endorsement *common.EndorsementEntry `protobuf:"bytes,6,opt,name=endorsement,proto3" json:"endorsement,omitempty"`
}

func (m *NewView) Reset()         { *m = NewView{} }
func (m *NewView) String() string { return proto.CompactTextString(m) }
func (*NewView) ProtoMessage()    {}
func (*NewView) Descriptor() ([]byte, []int) {
	return fileDescriptor_pbft_consensus, []int{6}
}

func (m *NewView) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *NewView) GetCurView() uint64 {
	if m != nil {
		return m.CurView
	}
	return 0
}

func (m *NewView) GetNextView() uint64 {
	if m != nil {
		return m.NextView
	}
	return 0
}

func (m *NewView) GetNewSequence() uint64 {
	if m != nil {
		return m.NewSequence
	}
	return 0
}

func (m *NewView) GetViewChangeMessages() []*ViewChange {
	if m != nil {
		return m.ViewChangeMessages
	}
	return nil
}

func (m *NewView) GetEndorsement() *common.EndorsementEntry {
	if m != nil {
		return m.Endorsement
	}
	return nil
}

// PrepareVoteSet represents a set of prepare votes
type PrepareVoteSet struct {
	View     uint64             `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Sequence uint64             `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Digest   []byte             `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Votes    map[string]*Prepare `protobuf:"bytes,4,rep,name=votes,proto3" json:"votes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Sum      uint64             `protobuf:"varint,5,opt,name=sum,proto3" json:"sum,omitempty"`
}

func (m *PrepareVoteSet) Reset()         { *m = PrepareVoteSet{} }
func (m *PrepareVoteSet) String() string { return proto.CompactTextString(m) }
func (*PrepareVoteSet) ProtoMessage()    {}
func (*PrepareVoteSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_pbft_consensus, []int{7}
}

func (m *PrepareVoteSet) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *PrepareVoteSet) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *PrepareVoteSet) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *PrepareVoteSet) GetVotes() map[string]*Prepare {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *PrepareVoteSet) GetSum() uint64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

// CommitVoteSet represents a set of commit votes
type CommitVoteSet struct {
	View     uint64          `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Sequence uint64          `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Digest   []byte          `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`
	Votes    map[string]*Commit `protobuf:"bytes,4,rep,name=votes,proto3" json:"votes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Sum      uint64          `protobuf:"varint,5,opt,name=sum,proto3" json:"sum,omitempty"`
}

func (m *CommitVoteSet) Reset()         { *m = CommitVoteSet{} }
func (m *CommitVoteSet) String() string { return proto.CompactTextString(m) }
func (*CommitVoteSet) ProtoMessage()    {}
func (*CommitVoteSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_pbft_consensus, []int{8}
}

func (m *CommitVoteSet) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *CommitVoteSet) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *CommitVoteSet) GetDigest() []byte {
	if m != nil {
		return m.Digest
	}
	return nil
}

func (m *CommitVoteSet) GetVotes() map[string]*Commit {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *CommitVoteSet) GetSum() uint64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

// ConsensusState represents the state of pbft instance
type ConsensusState struct {
	Id                string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	View              uint64                  `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	Sequence          uint64                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Step              PBFTStep                `protobuf:"varint,4,opt,name=step,proto3,enum=pbft.PBFTStep" json:"step,omitempty"`
	PrePrepare        *PrePrepare             `protobuf:"bytes,5,opt,name=pre_prepare,json=prePrepare,proto3" json:"pre_prepare,omitempty"`
	PrepareVoteSet    *PrepareVoteSet         `protobuf:"bytes,6,opt,name=prepare_vote_set,json=prepareVoteSet,proto3" json:"prepare_vote_set,omitempty"`
	CommitVoteSet     *CommitVoteSet          `protobuf:"bytes,7,opt,name=commit_vote_set,json=commitVoteSet,proto3" json:"commit_vote_set,omitempty"`
	ViewChangeVotes   map[string]*ViewChange  `protobuf:"bytes,8,rep,name=view_change_votes,json=viewChangeVotes,proto3" json:"view_change_votes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	NewViewVotes      map[string]*NewView     `protobuf:"bytes,9,rep,name=new_view_votes,json=newViewVotes,proto3" json:"new_view_votes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *ConsensusState) Reset()         { *m = ConsensusState{} }
func (m *ConsensusState) String() string { return proto.CompactTextString(m) }
func (*ConsensusState) ProtoMessage()    {}
func (*ConsensusState) Descriptor() ([]byte, []int) {
	return fileDescriptor_pbft_consensus, []int{9}
}

func (m *ConsensusState) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ConsensusState) GetView() uint64 {
	if m != nil {
		return m.View
	}
	return 0
}

func (m *ConsensusState) GetSequence() uint64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *ConsensusState) GetStep() PBFTStep {
	if m != nil {
		return m.Step
	}
	return PBFTStep_NEW_HEIGHT
}

func (m *ConsensusState) GetPrePrepare() *PrePrepare {
	if m != nil {
		return m.PrePrepare
	}
	return nil
}

func (m *ConsensusState) GetPrepareVoteSet() *PrepareVoteSet {
	if m != nil {
		return m.PrepareVoteSet
	}
	return nil
}

func (m *ConsensusState) GetCommitVoteSet() *CommitVoteSet {
	if m != nil {
		return m.CommitVoteSet
	}
	return nil
}

func (m *ConsensusState) GetViewChangeVotes() map[string]*ViewChange {
	if m != nil {
		return m.ViewChangeVotes
	}
	return nil
}

func (m *ConsensusState) GetNewViewVotes() map[string]*NewView {
	if m != nil {
		return m.NewViewVotes
	}
	return nil
}

// WalEntry represents an entry in the write-ahead log
type WalEntry struct {
	Type      WalEntryType `protobuf:"varint,1,opt,name=type,proto3,enum=pbft.WalEntryType" json:"type,omitempty"`
	Height    uint64       `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Data      []byte       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *WalEntry) Reset()         { *m = WalEntry{} }
func (m *WalEntry) String() string { return proto.CompactTextString(m) }
func (*WalEntry) ProtoMessage()    {}
func (*WalEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_pbft_consensus, []int{10}
}

func (m *WalEntry) GetType() WalEntryType {
	if m != nil {
		return m.Type
	}
	return WalEntryType_TIMEOUT_ENTRY
}

func (m *WalEntry) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *WalEntry) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// TimeoutInfo represents timeout information
type TimeoutInfo struct {
	Duration int64  `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
	Height   uint64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Round    uint64 `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
	Step     PBFTStep `protobuf:"varint,4,opt,name=step,proto3,enum=pbft.PBFTStep" json:"step,omitempty"`
}

func (m *TimeoutInfo) Reset()         { *m = TimeoutInfo{} }
func (m *TimeoutInfo) String() string { return proto.CompactTextString(m) }
func (*TimeoutInfo) ProtoMessage()    {}
func (*TimeoutInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_pbft_consensus, []int{11}
}

func (m *TimeoutInfo) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *TimeoutInfo) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *TimeoutInfo) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *TimeoutInfo) GetStep() PBFTStep {
	if m != nil {
		return m.Step
	}
	return PBFTStep_NEW_HEIGHT
}

func init() {
	proto.RegisterEnum("pbft.PBFTMsgType", PBFTMsgType_name, PBFTMsgType_value)
	proto.RegisterEnum("pbft.PBFTStep", PBFTStep_name, PBFTStep_value)
	proto.RegisterEnum("pbft.WalEntryType", WalEntryType_name, WalEntryType_value)
	proto.RegisterType((*ValidatorSet)(nil), "pbft.ValidatorSet")
	proto.RegisterType((*PBFTMsg)(nil), "pbft.PBFTMsg")
	proto.RegisterType((*PrePrepare)(nil), "pbft.PrePrepare")
	proto.RegisterMapType((map[string]*common.TxRWSet)(nil), "pbft.PrePrepare.TxsRwSetEntry")
	proto.RegisterType((*Prepare)(nil), "pbft.Prepare")
	proto.RegisterType((*Commit)(nil), "pbft.Commit")
	proto.RegisterType((*ViewChange)(nil), "pbft.ViewChange")
	proto.RegisterType((*NewView)(nil), "pbft.NewView")
	proto.RegisterType((*PrepareVoteSet)(nil), "pbft.PrepareVoteSet")
	proto.RegisterMapType((map[string]*Prepare)(nil), "pbft.PrepareVoteSet.VotesEntry")
	proto.RegisterType((*CommitVoteSet)(nil), "pbft.CommitVoteSet")
	proto.RegisterMapType((map[string]*Commit)(nil), "pbft.CommitVoteSet.VotesEntry")
	proto.RegisterType((*ConsensusState)(nil), "pbft.ConsensusState")
	proto.RegisterMapType((map[string]*ViewChange)(nil), "pbft.ConsensusState.ViewChangeVotesEntry")
	proto.RegisterMapType((map[string]*NewView)(nil), "pbft.ConsensusState.NewViewVotesEntry")
	proto.RegisterType((*WalEntry)(nil), "pbft.WalEntry")
	proto.RegisterType((*TimeoutInfo)(nil), "pbft.TimeoutInfo")
}

var fileDescriptor_pbft_consensus = []byte{
	// Placeholder for generated file descriptor
	// This would normally be generated by protoc
}

// Marshal and Unmarshal methods would be generated by protoc-gen-gogo
// These are placeholder implementations
func (m *ValidatorSet) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorSet) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorSet) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	// Placeholder implementation
	// Actual implementation would be generated by protoc-gen-gogo
	return 0, nil
}

func (m *ValidatorSet) Unmarshal(dAtA []byte) error {
	// Placeholder implementation
	// Actual implementation would be generated by protoc-gen-gogo
	return nil
}

func (m *ValidatorSet) Size() (n int) {
	// Placeholder implementation
	return 0
}

// Similar placeholder methods for other message types...
// In a real implementation, these would be generated by protoc-gen-gogo
