version: '2'

services:
  prometheus:
    image: prom/prometheus:v2.20.1
    restart: always
    hostname: prometheus_pbft  
    container_name: prom_pbft   # 修改容器名
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  
      - prometheus_data_pbft:/prometheus  # 修改数据卷名
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9091:9090'  # 修改主机端口
    depends_on:
      - influxdb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      prometheus_pbft:  # 改网络名
        aliases:
          - prometheus_pbft
        ipv4_address: 172.30.0.2  # 修改IP
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 100m

  grafana:
    image: grafana/grafana:7.1.2
    restart: always
    hostname: grafana_pbft
    container_name: grafana_pbft  # 修改容器名
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini  
      - grafana_data_pbft:/var/lib/grafana  # 修改数据卷名
      - ./index.html:/usr/share/grafana/public/views/index.html
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=chainmaker
    depends_on:
      - prometheus
      - mysql
    ports:
      - '3001:3000'  # 修改主机端口
    networks:
      prometheus_pbft:
        aliases:
          - grafana_pbft
        ipv4_address: 172.30.0.3  # 修改IP
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 100m

  influxdb:
    image: influxdb:1.8.1
    restart: always
    hostname: influxdb_pbft
    container_name: influxdb_pbft  # 修改容器名
    volumes:
      - influxdb_data_pbft:/var/lib/influxdb  # 修改数据卷名
    ports:
      - '8084:8083'  # 修改主机端口
      - '8087:8086'
      - '8091:8090'
    environment:
      - INFLUXDB_DB=prometheus_pbft
    networks:
      prometheus_pbft:
        aliases:
          - influxdb_pbft
        ipv4_address: 172.30.0.4  # 修改IP
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 100m

  mysql:
    image: mysql:8.0.22
    restart: always
    hostname: mysql_pbft
    container_name: mysql_pbft  # 修改容器名
    environment:
      - MYSQL_ROOT_PASSWORD=chainmaker
      - MYSQL_DATABASE=grafana_pbft
      - MYSQL_USER=chainmaker
      - MYSQL_PASSWORD=chainmaker
    volumes:
      - mysql_data_pbft:/var/lib/mysql  # 修改数据卷名
    ports:
      - '33307:3306'  # 修改主机端口
    networks:
      prometheus_pbft:
        aliases:
          - mysql_pbft
        ipv4_address: 172.30.0.5  # 修改IP
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 100m

networks:
  prometheus_pbft:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24  # 修改网段

volumes:
  grafana_data_pbft: {}
  prometheus_data_pbft: {}
  influxdb_data_pbft: {}
  mysql_data_pbft: {}