// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: syscontract/chain_config.proto

package syscontract

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// methods of chain config contract
type ChainConfigFunction int32

const (
	// get chain configuration
	ChainConfigFunction_GET_CHAIN_CONFIG ChainConfigFunction = 0
	// get the latest configuration block
	// the incoming block height must exist in the database
	ChainConfigFunction_GET_CHAIN_CONFIG_AT ChainConfigFunction = 1
	// update core
	ChainConfigFunction_CORE_UPDATE ChainConfigFunction = 2
	// update block
	ChainConfigFunction_BLOCK_UPDATE ChainConfigFunction = 3
	// add trusted certificate (org_id and root)
	ChainConfigFunction_TRUST_ROOT_ADD ChainConfigFunction = 4
	// [self] modify an individual's own trusted root certificate [org_id must exist in the original trust_roots,
	// and the new root certificate must be different from other certificates]
	ChainConfigFunction_TRUST_ROOT_UPDATE ChainConfigFunction = 5
	// delete trusted root certificate [org_ ID should be in trust_ The nodes in nodes need to be deleted]
	ChainConfigFunction_TRUST_ROOT_DELETE ChainConfigFunction = 6
	// organization add node address
	// org_id must already exist in nodes，you can add addresses in batches
	// the parameter is addresses. Single addresses are separated by ","
	// ip+port and peerid cannot be repeated
	// Deprecated , replace by NODE_ID_ADD
	ChainConfigFunction_NODE_ADDR_ADD ChainConfigFunction = 7
	// [self]the organization updates an address
	//[org_id and address must already exist in nodes, new_address is the new address. ip+port and peerId cannot be duplicated]
	// Deprecated , replace by NODE_ID_UPDATE
	ChainConfigFunction_NODE_ADDR_UPDATE ChainConfigFunction = 8
	// organization delete node address [org_id and address must already exist in nodes]
	// Deprecated , replace by NODE_ID_DELETE
	ChainConfigFunction_NODE_ADDR_DELETE ChainConfigFunction = 9
	// organization add node address in batches [org_id在nodes不存在，批量添加地址，参数为node_ids，单地址用逗号","隔开。nodeId不能重复]
	ChainConfigFunction_NODE_ORG_ADD ChainConfigFunction = 10
	// organization update
	// org_id must already exist in nodes，the parameter is addresses，Single addresses are separated by ","
	// ip+port and peerid cannot be repeated
	ChainConfigFunction_NODE_ORG_UPDATE ChainConfigFunction = 11
	// organization delete, org_id must already exist in nodes
	ChainConfigFunction_NODE_ORG_DELETE ChainConfigFunction = 12
	// add consensus parameters, key is not exit in ext_config
	ChainConfigFunction_CONSENSUS_EXT_ADD ChainConfigFunction = 13
	// update onsensus parameters, key exit in ext_config
	ChainConfigFunction_CONSENSUS_EXT_UPDATE ChainConfigFunction = 14
	// delete onsensus parameters, key exit in ext_config
	ChainConfigFunction_CONSENSUS_EXT_DELETE ChainConfigFunction = 15
	// add permission
	ChainConfigFunction_PERMISSION_ADD ChainConfigFunction = 16
	// update permission
	ChainConfigFunction_PERMISSION_UPDATE ChainConfigFunction = 17
	// delete permission
	ChainConfigFunction_PERMISSION_DELETE ChainConfigFunction = 18
	// organization add node_id
	// org_id must already exist in nodes，you can add node_id in batches
	// the parameter is node_ids. Single node_ids are separated by ","
	// node_id cannot be repeated
	ChainConfigFunction_NODE_ID_ADD ChainConfigFunction = 19
	// [self]the organization updates a node_ids
	//[org_id and node_ids must already exist in nodes, new_node_id is the new node_id. node_id cannot be duplicated]
	ChainConfigFunction_NODE_ID_UPDATE ChainConfigFunction = 20
	// organization delete node_id [org_id and node_id must already exist in nodes]
	ChainConfigFunction_NODE_ID_DELETE ChainConfigFunction = 21
	// add trusted member (org_id signcert role  node_id)
	ChainConfigFunction_TRUST_MEMBER_ADD ChainConfigFunction = 22
	// [self] modify an individual's own trusted member [node_id must exist in the original trust_members,
	// and the new trust member must be different from other trust members]
	ChainConfigFunction_TRUST_MEMBER_UPDATE ChainConfigFunction = 23
	// delete trusted member certificate [node_ ID should be in trust_ The nodes in nodes need to be deleted]
	ChainConfigFunction_TRUST_MEMBER_DELETE ChainConfigFunction = 24
	// alter address type
	ChainConfigFunction_ALTER_ADDR_TYPE ChainConfigFunction = 25
	// able or enable gas calc
	ChainConfigFunction_ENABLE_OR_DISABLE_GAS ChainConfigFunction = 26
	// set invoke base gas
	ChainConfigFunction_SET_INVOKE_BASE_GAS ChainConfigFunction = 27
	// set account manager admin
	ChainConfigFunction_SET_ACCOUNT_MANAGER_ADMIN ChainConfigFunction = 28
	// list permissions
	ChainConfigFunction_PERMISSION_LIST ChainConfigFunction = 29
	// update version
	ChainConfigFunction_UPDATE_VERSION ChainConfigFunction = 30
	// update `enable_manual_run` flag of multi sign
	ChainConfigFunction_MULTI_SIGN_ENABLE_MANUAL_RUN ChainConfigFunction = 31
	// enable only_creator_can_upgrade
	ChainConfigFunction_ENABLE_ONLY_CREATOR_UPGRADE ChainConfigFunction = 32
	// disable only_creator_can_upgrade
	ChainConfigFunction_DISABLE_ONLY_CREATOR_UPGRADE ChainConfigFunction = 33
	// set invoke gas price, continued with NO. `27`
	ChainConfigFunction_SET_INVOKE_GAS_PRICE ChainConfigFunction = 34
	// set install base price
	ChainConfigFunction_SET_INSTALL_BASE_GAS ChainConfigFunction = 35
	// set install gas price
	ChainConfigFunction_SET_INSTALL_GAS_PRICE ChainConfigFunction = 36
	// add new vm type to support list
	ChainConfigFunction_VM_SUPPORT_LIST_ADD ChainConfigFunction = 40
	// remove vm type in support list
	ChainConfigFunction_VM_SUPPORT_LIST_DEL ChainConfigFunction = 41
)

var ChainConfigFunction_name = map[int32]string{
	0:  "GET_CHAIN_CONFIG",
	1:  "GET_CHAIN_CONFIG_AT",
	2:  "CORE_UPDATE",
	3:  "BLOCK_UPDATE",
	4:  "TRUST_ROOT_ADD",
	5:  "TRUST_ROOT_UPDATE",
	6:  "TRUST_ROOT_DELETE",
	7:  "NODE_ADDR_ADD",
	8:  "NODE_ADDR_UPDATE",
	9:  "NODE_ADDR_DELETE",
	10: "NODE_ORG_ADD",
	11: "NODE_ORG_UPDATE",
	12: "NODE_ORG_DELETE",
	13: "CONSENSUS_EXT_ADD",
	14: "CONSENSUS_EXT_UPDATE",
	15: "CONSENSUS_EXT_DELETE",
	16: "PERMISSION_ADD",
	17: "PERMISSION_UPDATE",
	18: "PERMISSION_DELETE",
	19: "NODE_ID_ADD",
	20: "NODE_ID_UPDATE",
	21: "NODE_ID_DELETE",
	22: "TRUST_MEMBER_ADD",
	23: "TRUST_MEMBER_UPDATE",
	24: "TRUST_MEMBER_DELETE",
	25: "ALTER_ADDR_TYPE",
	26: "ENABLE_OR_DISABLE_GAS",
	27: "SET_INVOKE_BASE_GAS",
	28: "SET_ACCOUNT_MANAGER_ADMIN",
	29: "PERMISSION_LIST",
	30: "UPDATE_VERSION",
	31: "MULTI_SIGN_ENABLE_MANUAL_RUN",
	32: "ENABLE_ONLY_CREATOR_UPGRADE",
	33: "DISABLE_ONLY_CREATOR_UPGRADE",
	34: "SET_INVOKE_GAS_PRICE",
	35: "SET_INSTALL_BASE_GAS",
	36: "SET_INSTALL_GAS_PRICE",
	40: "VM_SUPPORT_LIST_ADD",
	41: "VM_SUPPORT_LIST_DEL",
}

var ChainConfigFunction_value = map[string]int32{
	"GET_CHAIN_CONFIG":             0,
	"GET_CHAIN_CONFIG_AT":          1,
	"CORE_UPDATE":                  2,
	"BLOCK_UPDATE":                 3,
	"TRUST_ROOT_ADD":               4,
	"TRUST_ROOT_UPDATE":            5,
	"TRUST_ROOT_DELETE":            6,
	"NODE_ADDR_ADD":                7,
	"NODE_ADDR_UPDATE":             8,
	"NODE_ADDR_DELETE":             9,
	"NODE_ORG_ADD":                 10,
	"NODE_ORG_UPDATE":              11,
	"NODE_ORG_DELETE":              12,
	"CONSENSUS_EXT_ADD":            13,
	"CONSENSUS_EXT_UPDATE":         14,
	"CONSENSUS_EXT_DELETE":         15,
	"PERMISSION_ADD":               16,
	"PERMISSION_UPDATE":            17,
	"PERMISSION_DELETE":            18,
	"NODE_ID_ADD":                  19,
	"NODE_ID_UPDATE":               20,
	"NODE_ID_DELETE":               21,
	"TRUST_MEMBER_ADD":             22,
	"TRUST_MEMBER_UPDATE":          23,
	"TRUST_MEMBER_DELETE":          24,
	"ALTER_ADDR_TYPE":              25,
	"ENABLE_OR_DISABLE_GAS":        26,
	"SET_INVOKE_BASE_GAS":          27,
	"SET_ACCOUNT_MANAGER_ADMIN":    28,
	"PERMISSION_LIST":              29,
	"UPDATE_VERSION":               30,
	"MULTI_SIGN_ENABLE_MANUAL_RUN": 31,
	"ENABLE_ONLY_CREATOR_UPGRADE":  32,
	"DISABLE_ONLY_CREATOR_UPGRADE": 33,
	"SET_INVOKE_GAS_PRICE":         34,
	"SET_INSTALL_BASE_GAS":         35,
	"SET_INSTALL_GAS_PRICE":        36,
	"VM_SUPPORT_LIST_ADD":          40,
	"VM_SUPPORT_LIST_DEL":          41,
}

func (x ChainConfigFunction) String() string {
	return proto.EnumName(ChainConfigFunction_name, int32(x))
}

func (ChainConfigFunction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_136926d916a77e0f, []int{0}
}

func init() {
	proto.RegisterEnum("syscontract.ChainConfigFunction", ChainConfigFunction_name, ChainConfigFunction_value)
}

func init() { proto.RegisterFile("syscontract/chain_config.proto", fileDescriptor_136926d916a77e0f) }

var fileDescriptor_136926d916a77e0f = []byte{
	// 578 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x18, 0x6d, 0xf9, 0xd9, 0xc0, 0xfb, 0x73, 0xdd, 0x96, 0xad, 0x6c, 0xcd, 0xc6, 0xcf, 0x05, 0x20,
	0xd1, 0x4a, 0xf0, 0x04, 0x6e, 0xe2, 0x05, 0x6b, 0x89, 0x1d, 0xd9, 0x4e, 0xc5, 0xb8, 0xb1, 0xda,
	0x0a, 0x4a, 0x85, 0x68, 0xaa, 0xae, 0x20, 0xf1, 0x16, 0xbc, 0x06, 0x6f, 0xc2, 0xe5, 0x2e, 0xb9,
	0x44, 0xed, 0x8b, 0x20, 0x3b, 0x2e, 0x4d, 0xbb, 0xdd, 0x25, 0xe7, 0x7c, 0xe7, 0xe4, 0x7c, 0xc7,
	0x72, 0x80, 0x77, 0xf5, 0xe3, 0x6a, 0x90, 0x8d, 0x67, 0xd3, 0xde, 0x60, 0xd6, 0x1e, 0x7c, 0xee,
	0x8d, 0xc6, 0x7a, 0x90, 0x8d, 0x3f, 0x8d, 0x86, 0xad, 0xc9, 0x34, 0x9b, 0x65, 0x68, 0xa7, 0xc0,
	0xbf, 0xfa, 0xb5, 0x0d, 0xaa, 0xbe, 0x99, 0xf1, 0xed, 0xc8, 0xf9, 0xb7, 0xf1, 0x60, 0x36, 0xca,
	0xc6, 0xa8, 0x06, 0x60, 0x48, 0x94, 0xf6, 0xdf, 0x61, 0xca, 0xb4, 0xcf, 0xd9, 0x39, 0x0d, 0x61,
	0x09, 0x1d, 0x82, 0xea, 0x26, 0xaa, 0xb1, 0x82, 0x65, 0x74, 0x00, 0x76, 0x7c, 0x2e, 0x88, 0x4e,
	0x93, 0x00, 0x2b, 0x02, 0xef, 0x20, 0x08, 0x76, 0x3b, 0x11, 0xf7, 0x2f, 0x96, 0xc8, 0x5d, 0x84,
	0xc0, 0xbe, 0x12, 0xa9, 0x54, 0x5a, 0x70, 0xae, 0x34, 0x0e, 0x02, 0x78, 0x0f, 0xd5, 0x41, 0xa5,
	0x80, 0xb9, 0xd1, 0xfb, 0x1b, 0x70, 0x40, 0x22, 0xa2, 0x08, 0xdc, 0x42, 0x15, 0xb0, 0xc7, 0x78,
	0x40, 0x8c, 0x56, 0x58, 0x83, 0x6d, 0x13, 0x73, 0x05, 0x39, 0xfd, 0x83, 0x75, 0xd4, 0xc9, 0x1f,
	0x9a, 0x48, 0x16, 0xe5, 0x22, 0xb4, 0x6a, 0x80, 0xaa, 0xe0, 0xe0, 0x3f, 0xe2, 0xc4, 0x3b, 0x6b,
	0xa0, 0xd3, 0xee, 0x9a, 0x44, 0x3e, 0x67, 0x92, 0x30, 0x99, 0x4a, 0x4d, 0xde, 0xe7, 0xf9, 0xf7,
	0xd0, 0x11, 0xa8, 0xad, 0xc3, 0xce, 0x65, 0xff, 0x26, 0xe3, 0xac, 0x0e, 0x4c, 0x0f, 0x09, 0x11,
	0x31, 0x95, 0x92, 0x72, 0x66, 0x7d, 0xa0, 0xb1, 0x2f, 0x60, 0xce, 0xa4, 0xb2, 0x01, 0x3b, 0x07,
	0x64, 0xca, 0xb6, 0x09, 0x69, 0x60, 0xe5, 0x55, 0x63, 0xb9, 0x04, 0x9c, 0xb6, 0x56, 0xc4, 0x9c,
	0xb0, 0x6e, 0x7a, 0xc9, 0x7b, 0x8d, 0x49, 0xdc, 0x21, 0x79, 0x87, 0x8f, 0xcc, 0xa1, 0xae, 0xa1,
	0xce, 0xe2, 0xf0, 0x06, 0xe1, 0x7c, 0x8e, 0x4c, 0x45, 0x38, 0x52, 0xb9, 0x81, 0xd0, 0xea, 0x32,
	0x21, 0xb0, 0x81, 0x1a, 0xa0, 0x4e, 0x18, 0xee, 0x44, 0xa6, 0x39, 0x1d, 0x50, 0x69, 0x1f, 0x43,
	0x2c, 0xe1, 0x63, 0x63, 0x24, 0x89, 0xd2, 0x94, 0x75, 0xf9, 0x05, 0xd1, 0x1d, 0x2c, 0x73, 0xe2,
	0x18, 0x35, 0x41, 0xc3, 0x10, 0xd8, 0xf7, 0x79, 0xca, 0x94, 0x8e, 0x31, 0xc3, 0xa1, 0xb5, 0x8d,
	0x29, 0x83, 0x27, 0xe6, 0x3b, 0x85, 0xfd, 0x23, 0x2a, 0x15, 0x6c, 0x9a, 0xc5, 0xf2, 0x84, 0xba,
	0x4b, 0x84, 0x21, 0xa0, 0x87, 0xce, 0xc0, 0x49, 0x9c, 0x46, 0x8a, 0x6a, 0x49, 0x43, 0xa6, 0x5d,
	0x8c, 0x18, 0xb3, 0x14, 0x47, 0x5a, 0xa4, 0x0c, 0x9e, 0xa2, 0x53, 0x70, 0xbc, 0x4c, 0xc7, 0xa2,
	0x4b, 0xed, 0x0b, 0x82, 0x15, 0x37, 0xbb, 0x86, 0x02, 0x07, 0x04, 0x9e, 0x19, 0x8b, 0x65, 0xe8,
	0x5b, 0x27, 0x9e, 0x98, 0x23, 0x2d, 0x6c, 0x11, 0x62, 0xa9, 0x13, 0x41, 0x7d, 0x02, 0x9f, 0xae,
	0x18, 0xa9, 0x70, 0x14, 0xad, 0x16, 0x7c, 0x66, 0x4a, 0x29, 0x32, 0x2b, 0xd1, 0x73, 0x53, 0x4a,
	0x37, 0xd6, 0x32, 0x4d, 0x12, 0x2e, 0x94, 0x5d, 0xce, 0x9e, 0xc7, 0x8b, 0xdb, 0x88, 0x80, 0x44,
	0xf0, 0x65, 0x67, 0xf8, 0x7b, 0xee, 0x95, 0xaf, 0xe7, 0x5e, 0xf9, 0xef, 0xdc, 0x2b, 0xff, 0x5c,
	0x78, 0xa5, 0xeb, 0x85, 0x57, 0xfa, 0xb3, 0xf0, 0x4a, 0xa0, 0x99, 0x4d, 0x87, 0x2d, 0x7b, 0xd5,
	0xbf, 0xf6, 0xbe, 0x7c, 0x9c, 0xb6, 0x26, 0xfd, 0x56, 0xe1, 0x92, 0x7f, 0x28, 0x52, 0xd9, 0x74,
	0xd8, 0x5e, 0xbd, 0xb6, 0x27, 0xfd, 0xd7, 0xc3, 0xac, 0xfd, 0xfd, 0x4d, 0xbb, 0x30, 0xdf, 0xdf,
	0xb2, 0x3f, 0x8a, 0xb7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x80, 0x47, 0x14, 0x0a, 0x4a, 0x04,
	0x00, 0x00,
}
