// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: common/contract.proto

package common

import (
	accesscontrol "chainmaker.org/chainmaker/pb-go/v2/accesscontrol"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// smart contract runtime, contains vm type and language type
type RuntimeType int32

const (
	RuntimeType_INVALID RuntimeType = 0
	// native implement in chainmaker-go
	RuntimeType_NATIVE RuntimeType = 1
	// vm-wasmer, language-c++
	RuntimeType_WASMER RuntimeType = 2
	// vm-wxvm, language-cpp
	RuntimeType_WXVM RuntimeType = 3
	// wasm interpreter in go
	RuntimeType_GASM RuntimeType = 4
	// vm-evm
	RuntimeType_EVM RuntimeType = 5
	// vm-docker, language-golang
	RuntimeType_DOCKER_GO RuntimeType = 6
	// vm-java, language-java
	RuntimeType_JAVA RuntimeType = 7
	// vm-go, language-go
	RuntimeType_GO RuntimeType = 8
)

var RuntimeType_name = map[int32]string{
	0: "INVALID",
	1: "NATIVE",
	2: "WASMER",
	3: "WXVM",
	4: "GASM",
	5: "EVM",
	6: "DOCKER_GO",
	7: "JAVA",
	8: "GO",
}

var RuntimeType_value = map[string]int32{
	"INVALID":   0,
	"NATIVE":    1,
	"WASMER":    2,
	"WXVM":      3,
	"GASM":      4,
	"EVM":       5,
	"DOCKER_GO": 6,
	"JAVA":      7,
	"GO":        8,
}

func (x RuntimeType) String() string {
	return proto.EnumName(RuntimeType_name, int32(x))
}

func (RuntimeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a1095c55e7168440, []int{0}
}

// current contract status
type ContractStatus int32

const (
	// normal, can be invoked
	ContractStatus_NORMAL ContractStatus = 0
	// frozen, cannot be invoked temporarily
	ContractStatus_FROZEN ContractStatus = 1
	// revoked, cannot be invoked permanently
	ContractStatus_REVOKED ContractStatus = 2
)

var ContractStatus_name = map[int32]string{
	0: "NORMAL",
	1: "FROZEN",
	2: "REVOKED",
}

var ContractStatus_value = map[string]int32{
	"NORMAL":  0,
	"FROZEN":  1,
	"REVOKED": 2,
}

func (x ContractStatus) String() string {
	return proto.EnumName(ContractStatus_name, int32(x))
}

func (ContractStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a1095c55e7168440, []int{1}
}

type Contract struct {
	// smart contract name, set by contract creator, can have multiple versions
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// smart contract version, set by contract creator, name + version should be unique
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// smart contract runtime type, set by contract creator
	RuntimeType RuntimeType `protobuf:"varint,3,opt,name=runtime_type,json=runtimeType,proto3,enum=common.RuntimeType" json:"runtime_type,omitempty"`
	//contract status
	Status ContractStatus `protobuf:"varint,4,opt,name=status,proto3,enum=common.ContractStatus" json:"status,omitempty"`
	//contract creator identity
	Creator *accesscontrol.MemberFull `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	//contract address
	Address string `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	Index   uint32 `protobuf:"varint,7,opt,name=index,proto3" json:"index,omitempty"`
	// the block height when contract installing request created, which is the first tx from users
	InstallCreateBlockHeight uint64 `protobuf:"varint,8,opt,name=install_create_block_height,json=installCreateBlockHeight,proto3" json:"install_create_block_height,omitempty"`
	// the install block height, it is the tx when contract execute init func
	// if install contract is normal, install_init_block_height = install_create_block_height
	InstallInitBlockHeight uint64 `protobuf:"varint,9,opt,name=install_init_block_height,json=installInitBlockHeight,proto3" json:"install_init_block_height,omitempty"`
	// the tx which contract installing request was created, it is the first tx from users
	InstallCreateTxId string `protobuf:"bytes,10,opt,name=install_create_tx_id,json=installCreateTxId,proto3" json:"install_create_tx_id,omitempty"`
	// if install contract is normal, install_init_tx_id = install_create_tx_id
	InstallInitTxId string `protobuf:"bytes,11,opt,name=install_init_tx_id,json=installInitTxId,proto3" json:"install_init_tx_id,omitempty"`
	// the last upgrading request created block height, if there has been no upgrade, this will be 0
	UpgradeCreateBlockHeight uint64 `protobuf:"varint,12,opt,name=upgrade_create_block_height,json=upgradeCreateBlockHeight,proto3" json:"upgrade_create_block_height,omitempty"`
	// the last upgrading request init block height,
	// if the request is normal,  upgrade_init_block_height = upgrade_create_block_height
	UpgradeInitBlockHeight uint64 `protobuf:"varint,13,opt,name=upgrade_init_block_height,json=upgradeInitBlockHeight,proto3" json:"upgrade_init_block_height,omitempty"`
	// the last upgrading request created tx id, if there has been no upgrade, this will be empty
	UpgradeCreateTxId string `protobuf:"bytes,14,opt,name=upgrade_create_tx_id,json=upgradeCreateTxId,proto3" json:"upgrade_create_tx_id,omitempty"`
	// the last upgrading request init tx id,
	// if the request is normal,  upgrade_init_tx_id = upgrade_create_tx_id
	UpgradeInitTxId string `protobuf:"bytes,15,opt,name=upgrade_init_tx_id,json=upgradeInitTxId,proto3" json:"upgrade_init_tx_id,omitempty"`
}

func (m *Contract) Reset()         { *m = Contract{} }
func (m *Contract) String() string { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()    {}
func (*Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1095c55e7168440, []int{0}
}
func (m *Contract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Contract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract.Merge(m, src)
}
func (m *Contract) XXX_Size() int {
	return m.Size()
}
func (m *Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Contract proto.InternalMessageInfo

func (m *Contract) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Contract) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Contract) GetRuntimeType() RuntimeType {
	if m != nil {
		return m.RuntimeType
	}
	return RuntimeType_INVALID
}

func (m *Contract) GetStatus() ContractStatus {
	if m != nil {
		return m.Status
	}
	return ContractStatus_NORMAL
}

func (m *Contract) GetCreator() *accesscontrol.MemberFull {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *Contract) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Contract) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Contract) GetInstallCreateBlockHeight() uint64 {
	if m != nil {
		return m.InstallCreateBlockHeight
	}
	return 0
}

func (m *Contract) GetInstallInitBlockHeight() uint64 {
	if m != nil {
		return m.InstallInitBlockHeight
	}
	return 0
}

func (m *Contract) GetInstallCreateTxId() string {
	if m != nil {
		return m.InstallCreateTxId
	}
	return ""
}

func (m *Contract) GetInstallInitTxId() string {
	if m != nil {
		return m.InstallInitTxId
	}
	return ""
}

func (m *Contract) GetUpgradeCreateBlockHeight() uint64 {
	if m != nil {
		return m.UpgradeCreateBlockHeight
	}
	return 0
}

func (m *Contract) GetUpgradeInitBlockHeight() uint64 {
	if m != nil {
		return m.UpgradeInitBlockHeight
	}
	return 0
}

func (m *Contract) GetUpgradeCreateTxId() string {
	if m != nil {
		return m.UpgradeCreateTxId
	}
	return ""
}

func (m *Contract) GetUpgradeInitTxId() string {
	if m != nil {
		return m.UpgradeInitTxId
	}
	return ""
}

func init() {
	proto.RegisterEnum("common.RuntimeType", RuntimeType_name, RuntimeType_value)
	proto.RegisterEnum("common.ContractStatus", ContractStatus_name, ContractStatus_value)
	proto.RegisterType((*Contract)(nil), "common.Contract")
}

func init() { proto.RegisterFile("common/contract.proto", fileDescriptor_a1095c55e7168440) }

var fileDescriptor_a1095c55e7168440 = []byte{
	// 580 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xcf, 0x4e, 0xdb, 0x4c,
	0x14, 0xc5, 0xe3, 0x90, 0x38, 0xe1, 0x86, 0x3f, 0xfe, 0xe6, 0xa3, 0x68, 0x00, 0x29, 0x8a, 0xba,
	0x4a, 0xa9, 0x6a, 0x4b, 0xa0, 0x56, 0xea, 0x82, 0x85, 0x01, 0x43, 0x53, 0x08, 0x91, 0x06, 0x14,
	0x2a, 0xa4, 0xca, 0x72, 0xec, 0x51, 0xb0, 0xb0, 0x3d, 0xd6, 0x78, 0x82, 0xe0, 0x2d, 0xfa, 0x32,
	0x7d, 0x87, 0x2e, 0x59, 0x76, 0x59, 0xc1, 0x8b, 0x54, 0x9e, 0xb1, 0x45, 0x4c, 0xd9, 0xcd, 0x9d,
	0xfb, 0x3b, 0x3e, 0xe7, 0x48, 0x1e, 0x78, 0xe3, 0xb3, 0x38, 0x66, 0x89, 0xe5, 0xb3, 0x44, 0x70,
	0xcf, 0x17, 0x66, 0xca, 0x99, 0x60, 0x48, 0x57, 0xd7, 0x9b, 0x9b, 0x9e, 0xef, 0xd3, 0x2c, 0x93,
	0x5b, 0x16, 0x59, 0x31, 0x8d, 0x27, 0x94, 0x2b, 0xe6, 0xed, 0xcf, 0x26, 0xb4, 0x0f, 0x0a, 0x19,
	0x42, 0xd0, 0x48, 0xbc, 0x98, 0x62, 0xad, 0xa7, 0xf5, 0x17, 0x89, 0x3c, 0x23, 0x0c, 0xad, 0x5b,
	0xca, 0xb3, 0x90, 0x25, 0xb8, 0x2e, 0xaf, 0xcb, 0x11, 0x7d, 0x82, 0x25, 0x3e, 0x4b, 0x44, 0x18,
	0x53, 0x57, 0xdc, 0xa7, 0x14, 0x2f, 0xf4, 0xb4, 0xfe, 0xca, 0xce, 0xff, 0xa6, 0x72, 0x35, 0x89,
	0xda, 0x5d, 0xdc, 0xa7, 0x94, 0x74, 0xf8, 0xf3, 0x80, 0x4c, 0xd0, 0x33, 0xe1, 0x89, 0x59, 0x86,
	0x1b, 0x52, 0xb1, 0x5e, 0x2a, 0xca, 0x1c, 0xe7, 0x72, 0x4b, 0x0a, 0x0a, 0xed, 0x42, 0xcb, 0xe7,
	0xd4, 0x13, 0x8c, 0xe3, 0x66, 0x4f, 0xeb, 0x77, 0x76, 0x36, 0xcc, 0x4a, 0x21, 0x73, 0x28, 0x0b,
	0x1d, 0xcd, 0xa2, 0x88, 0x94, 0x64, 0x1e, 0xdb, 0x0b, 0x02, 0x4e, 0xb3, 0x0c, 0xeb, 0x2a, 0x76,
	0x31, 0xa2, 0x35, 0x68, 0x86, 0x49, 0x40, 0xef, 0x70, 0xab, 0xa7, 0xf5, 0x97, 0x89, 0x1a, 0xd0,
	0x1e, 0x6c, 0x85, 0x49, 0x26, 0xbc, 0x28, 0x72, 0xe5, 0x27, 0xa8, 0x3b, 0x89, 0x98, 0x7f, 0xe3,
	0x5e, 0xd3, 0x70, 0x7a, 0x2d, 0x70, 0xbb, 0xa7, 0xf5, 0x1b, 0x04, 0x17, 0xc8, 0x81, 0x24, 0xf6,
	0x73, 0xe0, 0x8b, 0xdc, 0xa3, 0xcf, 0xb0, 0x51, 0xca, 0xc3, 0x24, 0x14, 0x55, 0xf1, 0xa2, 0x14,
	0xaf, 0x17, 0xc0, 0x20, 0x09, 0xc5, 0xbc, 0xd4, 0x82, 0xb5, 0x17, 0xce, 0xe2, 0xce, 0x0d, 0x03,
	0x0c, 0x32, 0xf6, 0x7f, 0x15, 0xcb, 0x8b, 0xbb, 0x41, 0x80, 0xde, 0x03, 0xaa, 0x78, 0x29, 0xbc,
	0x23, 0xf1, 0xd5, 0x39, 0x13, 0x09, 0xef, 0xc1, 0xd6, 0x2c, 0x9d, 0x72, 0x2f, 0xa0, 0xaf, 0xf6,
	0x5a, 0x52, 0xbd, 0x0a, 0xe4, 0xd5, 0x5e, 0xa5, 0xfc, 0xdf, 0x5e, 0xcb, 0xaa, 0x57, 0x01, 0xbc,
	0xd2, 0xeb, 0x85, 0xb3, 0x0a, 0xba, 0xa2, 0x7a, 0x55, 0x2c, 0xcb, 0x5e, 0x15, 0x2f, 0x85, 0xaf,
	0xaa, 0x5e, 0x73, 0x26, 0x39, 0xbc, 0x9d, 0x42, 0x67, 0xee, 0x07, 0x43, 0x1d, 0x68, 0x0d, 0xce,
	0xc6, 0xf6, 0xe9, 0xe0, 0xd0, 0xa8, 0x21, 0x00, 0xfd, 0xcc, 0xbe, 0x18, 0x8c, 0x1d, 0x43, 0xcb,
	0xcf, 0x97, 0xf6, 0xf9, 0xd0, 0x21, 0x46, 0x1d, 0xb5, 0xa1, 0x71, 0xf9, 0x6d, 0x3c, 0x34, 0x16,
	0xf2, 0xd3, 0xb1, 0x7d, 0x3e, 0x34, 0x1a, 0xa8, 0x05, 0x0b, 0xce, 0x78, 0x68, 0x34, 0xd1, 0x32,
	0x2c, 0x1e, 0x8e, 0x0e, 0x4e, 0x1c, 0xe2, 0x1e, 0x8f, 0x0c, 0x3d, 0x27, 0xbe, 0xda, 0x63, 0xdb,
	0x68, 0x21, 0x1d, 0xea, 0xc7, 0x23, 0xa3, 0xbd, 0xfd, 0x11, 0x56, 0xaa, 0x3f, 0xa8, 0xf4, 0x19,
	0x91, 0xa1, 0x7d, 0xaa, 0x3c, 0x8f, 0xc8, 0xe8, 0xca, 0x39, 0x33, 0xb4, 0x3c, 0x0c, 0x71, 0xc6,
	0xa3, 0x13, 0xe7, 0xd0, 0xa8, 0xef, 0x7f, 0xff, 0xf5, 0xd8, 0xd5, 0x1e, 0x1e, 0xbb, 0xda, 0x9f,
	0xc7, 0xae, 0xf6, 0xe3, 0xa9, 0x5b, 0x7b, 0x78, 0xea, 0xd6, 0x7e, 0x3f, 0x75, 0x6b, 0x80, 0x19,
	0x9f, 0x9a, 0xfe, 0xb5, 0x17, 0x26, 0xb1, 0x77, 0x93, 0x3f, 0xc8, 0x49, 0xf1, 0x10, 0xae, 0xde,
	0xcd, 0xdd, 0x32, 0x3e, 0xb5, 0x9e, 0x47, 0x2b, 0x9d, 0x7c, 0x98, 0x32, 0xeb, 0x76, 0xc7, 0x52,
	0xe8, 0x44, 0x97, 0xcf, 0x78, 0xf7, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x08, 0xf5, 0x8d, 0x41,
	0x03, 0x04, 0x00, 0x00,
}

func (m *Contract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Contract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Contract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UpgradeInitTxId) > 0 {
		i -= len(m.UpgradeInitTxId)
		copy(dAtA[i:], m.UpgradeInitTxId)
		i = encodeVarintContract(dAtA, i, uint64(len(m.UpgradeInitTxId)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.UpgradeCreateTxId) > 0 {
		i -= len(m.UpgradeCreateTxId)
		copy(dAtA[i:], m.UpgradeCreateTxId)
		i = encodeVarintContract(dAtA, i, uint64(len(m.UpgradeCreateTxId)))
		i--
		dAtA[i] = 0x72
	}
	if m.UpgradeInitBlockHeight != 0 {
		i = encodeVarintContract(dAtA, i, uint64(m.UpgradeInitBlockHeight))
		i--
		dAtA[i] = 0x68
	}
	if m.UpgradeCreateBlockHeight != 0 {
		i = encodeVarintContract(dAtA, i, uint64(m.UpgradeCreateBlockHeight))
		i--
		dAtA[i] = 0x60
	}
	if len(m.InstallInitTxId) > 0 {
		i -= len(m.InstallInitTxId)
		copy(dAtA[i:], m.InstallInitTxId)
		i = encodeVarintContract(dAtA, i, uint64(len(m.InstallInitTxId)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.InstallCreateTxId) > 0 {
		i -= len(m.InstallCreateTxId)
		copy(dAtA[i:], m.InstallCreateTxId)
		i = encodeVarintContract(dAtA, i, uint64(len(m.InstallCreateTxId)))
		i--
		dAtA[i] = 0x52
	}
	if m.InstallInitBlockHeight != 0 {
		i = encodeVarintContract(dAtA, i, uint64(m.InstallInitBlockHeight))
		i--
		dAtA[i] = 0x48
	}
	if m.InstallCreateBlockHeight != 0 {
		i = encodeVarintContract(dAtA, i, uint64(m.InstallCreateBlockHeight))
		i--
		dAtA[i] = 0x40
	}
	if m.Index != 0 {
		i = encodeVarintContract(dAtA, i, uint64(m.Index))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintContract(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x32
	}
	if m.Creator != nil {
		{
			size, err := m.Creator.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintContract(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.Status != 0 {
		i = encodeVarintContract(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x20
	}
	if m.RuntimeType != 0 {
		i = encodeVarintContract(dAtA, i, uint64(m.RuntimeType))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintContract(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintContract(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintContract(dAtA []byte, offset int, v uint64) int {
	offset -= sovContract(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Contract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	if m.RuntimeType != 0 {
		n += 1 + sovContract(uint64(m.RuntimeType))
	}
	if m.Status != 0 {
		n += 1 + sovContract(uint64(m.Status))
	}
	if m.Creator != nil {
		l = m.Creator.Size()
		n += 1 + l + sovContract(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	if m.Index != 0 {
		n += 1 + sovContract(uint64(m.Index))
	}
	if m.InstallCreateBlockHeight != 0 {
		n += 1 + sovContract(uint64(m.InstallCreateBlockHeight))
	}
	if m.InstallInitBlockHeight != 0 {
		n += 1 + sovContract(uint64(m.InstallInitBlockHeight))
	}
	l = len(m.InstallCreateTxId)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	l = len(m.InstallInitTxId)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	if m.UpgradeCreateBlockHeight != 0 {
		n += 1 + sovContract(uint64(m.UpgradeCreateBlockHeight))
	}
	if m.UpgradeInitBlockHeight != 0 {
		n += 1 + sovContract(uint64(m.UpgradeInitBlockHeight))
	}
	l = len(m.UpgradeCreateTxId)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	l = len(m.UpgradeInitTxId)
	if l > 0 {
		n += 1 + l + sovContract(uint64(l))
	}
	return n
}

func sovContract(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozContract(x uint64) (n int) {
	return sovContract(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Contract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContract
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Contract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Contract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RuntimeType", wireType)
			}
			m.RuntimeType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RuntimeType |= RuntimeType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= ContractStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthContract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Creator == nil {
				m.Creator = &accesscontrol.MemberFull{}
			}
			if err := m.Creator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			m.Index = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Index |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstallCreateBlockHeight", wireType)
			}
			m.InstallCreateBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InstallCreateBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstallInitBlockHeight", wireType)
			}
			m.InstallInitBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InstallInitBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstallCreateTxId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InstallCreateTxId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InstallInitTxId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InstallInitTxId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpgradeCreateBlockHeight", wireType)
			}
			m.UpgradeCreateBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpgradeCreateBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpgradeInitBlockHeight", wireType)
			}
			m.UpgradeInitBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpgradeInitBlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpgradeCreateTxId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpgradeCreateTxId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpgradeInitTxId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpgradeInitTxId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipContract(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContract
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipContract(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowContract
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContract
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContract
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthContract
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupContract
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthContract
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthContract        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowContract          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupContract = fmt.Errorf("proto: unexpected end of group")
)
